import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const myFont = localFont({
  src: [
    { path: '../public/fonts/ProximaNova-Semibold.ttf', weight: '600', style: 'normal' },
    { path: '../public/fonts/ProximaNova-Bold.ttf', weight: '700', style: 'normal' },
    { path: '../public/fonts/ProximaNova-Extrabld.ttf', weight: '800', style: 'normal' },
    { path: '../public/fonts/ProximaNova-Black.ttf', weight: '900', style: 'normal' },
  ],
  variable: '--font-proximanova',   // создаст CSS‑переменную для удобного использования
  display: 'swap',         // стратегия отображения (swap/fallback/auto)
});

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ['cyrillic', 'latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${montSerrat.variable} ${myFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
